services:
  backend:
    build: .
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres_service
      - redis_service

  celery_worker:
    build: .
    env_file: .env
    command: uv run celery -A root worker -l info
    depends_on:
      - redis_service
      - postgres_service

  celery_beat:
    build: .
    env_file: .env
    command: uv run celery -A root beat -l info
    depends_on:
      - redis_service
      - postgres_service

  postgres_service:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=test123
      - POSTGRES_DB=edumrx_test
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"

  redis_service:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  media:
  pgdata: