# Generated by Django 6.0.5 on 2026-05-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_accountrecovery_notificationrecipient_room_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='max_students',
        ),
        migrations.AlterField(
            model_name='group',
            name='lesson_days',
            field=models.JSONField(default=list, help_text='List of week day integers (0=Monday ... 6=Sunday)'),
        ),
        migrations.DeleteModel(
            name='AccountRecovery',
        ),
    ]
