# Generated by Django 6.0.5 on 2026-06-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_course_center_group_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Kenglik (Latitude)'),
        ),
        migrations.AddField(
            model_name='student',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Uzunlik (Longitude)'),
        ),
    ]
