# Generated by Django 6.0.5 on 2026-06-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_student_latitude_student_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='marked_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='lesson',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
