# Generated by Django 6.0.5 on 2026-05-30 12:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_remove_group_max_students_alter_group_lesson_days_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('slug', models.CharField(max_length=255, unique=True, verbose_name='Slug')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='centers/logos/%Y/', verbose_name='Logo')),
                ('address', models.TextField(blank=True, verbose_name='Manzil')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('suspended', "To'xtatilgan"), ('inactive', 'Nofaol')], default='active', max_length=20, verbose_name='Holat')),
                ('subscription_expires', models.DateField(blank=True, null=True, verbose_name='Tarif tugash sanasi')),
            ],
            options={
                'verbose_name': "O'quv markazi",
                'verbose_name_plural': "O'quv markazlari",
                'db_table': 'centers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CenterStaff',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
            ],
            options={
                'verbose_name': 'Markaz xodimi',
                'verbose_name_plural': 'Markaz xodimlari',
                'db_table': 'center_staff',
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.TextField(blank=True, verbose_name='Manzil')),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('occupation', models.CharField(blank=True, max_length=255, verbose_name='Kasbi')),
            ],
            options={
                'verbose_name': 'Ota-ona',
                'verbose_name_plural': 'Ota-onalar',
                'db_table': 'parents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('specialization', models.CharField(blank=True, max_length=255, verbose_name='Mutaxassislik')),
                ('experience', models.PositiveSmallIntegerField(default=0, verbose_name='Tajriba (yil)')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Maosh')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana")),
            ],
            options={
                'verbose_name': "O'qituvchi",
                'verbose_name_plural': "O'qituvchilar",
                'db_table': 'teachers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-created_at'], 'verbose_name': 'Talaba', 'verbose_name_plural': 'Talabalar'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana"),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrolled_at',
            field=models.DateField(auto_now_add=True, verbose_name="Ro'yxatga olingan sana"),
        ),
        migrations.AlterField(
            model_name='student',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Faol'), ('inactive', 'Nofaol'), ('graduated', 'Bitirgan'), ('suspended', "To'xtatilgan")], default='active', max_length=20, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='user',
            name='backup_phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name="Qo'shimcha telefon"),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Xodim'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Familiya'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, unique=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('director', 'Direktor'), ('admin', 'Admin (Reception)'), ('teacher', "O'qituvchi"), ('student', 'Talaba'), ('parent', 'Ota-ona')], default='student', max_length=20, verbose_name='Rol'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_role_0ace22_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='users_is_acti_847b48_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-created_at'], name='users_created_30b417_idx'),
        ),
        migrations.AlterModelTable(
            name='student',
            table='students',
        ),
        migrations.AddField(
            model_name='center',
            name='director',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'director'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_centers', to=settings.AUTH_USER_MODEL, verbose_name='Direktor'),
        ),
        migrations.AddField(
            model_name='student',
            name='center',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='apps.center', verbose_name="O'quv markazi"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='centerstaff',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='apps.center'),
        ),
        migrations.AddField(
            model_name='centerstaff',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parent',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='apps.parent', verbose_name='Ota-ona'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['status'], name='students_status_3ac771_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['center'], name='students_center__7e81bd_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['-created_at'], name='students_created_48b853_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['center', 'status'], name='students_center__e72bb2_idx'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='centers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='apps.center'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_groups', to='apps.teacher'),
        ),
        migrations.AddIndex(
            model_name='center',
            index=models.Index(fields=['status'], name='centers_status_f409cc_idx'),
        ),
        migrations.AddIndex(
            model_name='center',
            index=models.Index(fields=['slug'], name='centers_slug_4e1712_idx'),
        ),
    ]
